from __future__ import annotations

import difflib
import json
from pathlib import Path

import pytest

from src.ai.intent_router import IntentRouter, render_invocation


GOLDEN_DIR = Path(__file__).resolve().parent / "snapshots"
GOLDEN_NAME = "intent_router_deterministic_routes"
REQUESTS = (
    "redo issue 12 with fabrikam only",
    "compare issue 11 and issue 12",
    "kb changelog since 2026-W20",
    'search archive for "ud chunking"',
    "show semantic history for rollout regression",
    "confirm issue 12",
    "publish gate for issue 12",
    "review issue 12",
    "history for issue 12",
    "show evidence for WI 12345",
    "investigate icm 12345",
    "investigate account acme-prod",
    "follow up on transcript thread-abc-123",
    "catch me up",
    "give me a catchup",
    "show me a catchup",
    "bring me up to speed",
    "bring me up to date",
    "show manifest for issue 12",
    "show contradictions",
    "show me contradictions",
    "what contradictions exist?",
    "list editions",
    "what editions are available?",
    "list workstreams",
    "which editions are configured?",
    "what workstreams are there?",
    "list dris",
    "show registry",
    "which workstreams are configured?",
    "who are the dris?",
    "list milestones",
    "who are the owners?",
    "assess milestones",
    "show milestone status",
    "show me milestone status",
    "what milestones are at risk?",
    "review sections for issue 12",
    "dependency proposals",
    "show dependencies",
    "show me dependencies",
    "show me the dependency proposals",
    "give me the dependency proposals",
    "what dependencies need review?",
    "prep brief",
    "prepare prep brief",
    "prepare me for the meeting",
    "prep me for the meeting",
    "show me prep brief",
    "show me the prep brief",
    "give me prep brief",
    "give me the prep brief",
    "help me prepare for the meeting",
    "owner pack for priya",
    "show owner pack for Priya",
    "give me owner pack for jordan",
    "show me Priya's owner pack",
    "give me Jordan's owner pack",
    "show deck companion for issue 12",
    "review proposals for issue 12",
    "fleet health",
    "how is the fleet doing?",
    "how are all programs doing?",
    "trust calibration",
    "how much do we trust the system?",
    "how much can we trust the system?",
    "how trustworthy is the system?",
    "how trustworthy are we?",
    "prompt learning summary",
    "what did we learn from prompts?",
    "what have we learned from prompts?",
    "preview decision debt follow-ups",
    "apply decision debt follow-ups",
    "decision debt",
    "show me pending decision follow-ups",
    "preview pending 14-day decision nudges",
    "apply all approved decision follow-ups",
    "what decisions are due?",
    "which decisions need follow-up?",
    "author salience",
    "how much attention are we paying?",
    "what changed since Friday on UD chunking?",
    "status",
    "our status",
    "status please",
    "give me status",
    "give us status",
    "give me the status",
    "give us the status",
    "show status",
    "show me the status",
    "show me our status",
    "what is the status?",
    "what's the status?",
    "what is our status?",
    "what's our status?",
    "how is the status?",
    "show me status",
    "show us status",
    "how's the status?",
    "show us the status",
    "how is our status?",
    "how's our status?",
    "give me a status update",
    "where do we stand?",
    "brief me",
    "give me today's brief",
    "what's my brief today?",
    "brief me for today",
    "next",
    "what should i do",
    "what should i do next?",
    "what can i do next?",
    "what's next?",
    "what is next?",
    "what do we do next?",
    "what should we do next?",
    "what should i focus on?",
    "what should i work on next?",
    "what do i do now?",
    "what's my next move?",
    "next move",
    "launch readiness",
    "are we ready?",
    "are we ready to launch?",
    "how ready are we?",
    "ready for launch?",
    "ready for the launch?",
    "how ready is launch?",
    "how ready is the launch?",
    "am i ready for release?",
    "ready for the release?",
    "how ready is the release?",
    "risk register",
    "show me risks",
    "what are the top risks?",
    "what risks are open?",
    "show me current risks",
    "which risks need attention?",
    "show assumptions",
    "show me assumptions",
    "give me assumptions",
    "what assumptions are open?",
    "current assumptions",
    "claims",
    "show me claims",
    "calibration",
    "how calibrated are we?",
    "forecast accuracy",
    "show forecast accuracy",
    "show me forecast accuracy",
    "how accurate are our forecasts?",
    "signals",
    "show me signals",
    "show me pending signals",
    "show actions",
    "show me actions",
    "vitality",
    "how healthy is the program?",
    "how healthy are we?",
    "show me program health",
    "how fresh is the program?",
    "ado status",
    "ado reconcile",
    "storage stats",
    "storage check",
    "how much storage do we have?",
    "how is storage doing?",
    "backfill using hybrid",
    "freshness",
    "show me freshness",
    "how fresh is the data?",
    "how current is the data?",
    "health check",
    "check health",
    "check the health",
    "are things healthy?",
    "is everything healthy?",
    "how healthy are things?",
    "how healthy is everything?",
    "is the edition healthy?",
    "how healthy is the edition?",
)
READ_ONLY_REQUESTS = (
    'search archive for "ud chunking"',
    "kb changelog since 2026-W20",
    "show semantic history for rollout regression",
    "review issue 12",
    "history for issue 12",
    "show evidence for WI 12345",
    "investigate icm 12345",
    "investigate account acme-prod",
    "catch me up",
    "give me a catchup",
    "show me a catchup",
    "bring me up to speed",
    "bring me up to date",
    "show manifest for issue 12",
    "show contradictions",
    "show me contradictions",
    "what contradictions exist?",
    "list editions",
    "which editions are configured?",
    "what editions are available?",
    "list workstreams",
    "which workstreams are configured?",
    "what workstreams are there?",
    "list dris",
    "show registry",
    "who are the owners?",
    "who are the dris?",
    "list milestones",
    "assess milestones",
    "show milestone status",
    "show me milestone status",
    "what milestones are at risk?",
    "review sections for issue 12",
    "dependency proposals",
    "show dependencies",
    "show me dependencies",
    "what dependencies need review?",
    "prep brief",
    "owner pack for priya",
    "show deck companion for issue 12",
    "review proposals for issue 12",
    "fleet health",
    "how is the fleet doing?",
    "how are all programs doing?",
    "trust calibration",
    "how much do we trust the system?",
    "how much can we trust the system?",
    "how trustworthy is the system?",
    "how trustworthy are we?",
    "prompt learning summary",
    "what did we learn from prompts?",
    "what have we learned from prompts?",
    "decision debt",
    "show me pending decision follow-ups",
    "preview pending 14-day decision nudges",
    "what decisions are due?",
    "which decisions need follow-up?",
    "author salience",
    "how much attention are we paying?",
    "what changed since Friday on UD chunking?",
    "status",
    "our status",
    "status please",
    "give me status",
    "give us status",
    "give me the status",
    "give us the status",
    "show status",
    "show me the status",
    "show me our status",
    "what is the status?",
    "what's the status?",
    "what is our status?",
    "what's our status?",
    "how is the status?",
    "show me status",
    "show us status",
    "how's the status?",
    "show us the status",
    "how is our status?",
    "how's our status?",
    "give me a status update",
    "where do we stand?",
    "brief me",
    "give me today's brief",
    "what's my brief today?",
    "brief me for today",
    "next",
    "what should i do",
    "what should i do next?",
    "what can i do next?",
    "what's next?",
    "what is next?",
    "what do we do next?",
    "what should we do next?",
    "what should i focus on?",
    "what should i work on next?",
    "what do i do now?",
    "what's my next move?",
    "next move",
    "launch readiness",
    "are we ready?",
    "are we ready to launch?",
    "how ready are we?",
    "ready for launch?",
    "ready for the launch?",
    "how ready is launch?",
    "how ready is the launch?",
    "am i ready for release?",
    "ready for the release?",
    "how ready is the release?",
    "risk register",
    "show me risks",
    "what are the top risks?",
    "what risks are open?",
    "show me current risks",
    "which risks need attention?",
    "show assumptions",
    "show me assumptions",
    "give me assumptions",
    "what assumptions are open?",
    "current assumptions",
    "claims",
    "show me claims",
    "calibration",
    "how calibrated are we?",
    "forecast accuracy",
    "show forecast accuracy",
    "show me forecast accuracy",
    "how accurate are our forecasts?",
    "signals",
    "show me signals",
    "show me pending signals",
    "show actions",
    "show me actions",
    "vitality",
    "how healthy is the program?",
    "how healthy are we?",
    "show me program health",
    "how fresh is the program?",
    "ado status",
    "ado reconcile",
    "storage stats",
    "storage check",
    "how much storage do we have?",
    "how is storage doing?",
    "backfill using hybrid",
    "freshness",
    "show me freshness",
    "how fresh is the data?",
    "how current is the data?",
    "health check",
    "check health",
    "check the health",
    "are things healthy?",
    "is everything healthy?",
    "how healthy are things?",
    "how healthy is everything?",
    "is the edition healthy?",
    "how healthy is the edition?",
)
READ_ONLY_COMMAND_FAMILIES = {
    "actions",
    "ado",
    "audit",
    "backfill",
    "brief",
    "calibration",
    "catchup",
    "claims",
    "deck-companion",
    "decisions",
    "dependencies",
    "doctor",
    "evidence",
    "fleet",
    "freshness",
    "history",
    "investigate",
    "kb",
    "list",
    "manifest",
    "milestones",
    "next",
    "owner-pack",
    "prep",
    "readiness",
    "reconcile",
    "registry",
    "review-full",
    "review-proposals",
    "review-sections",
    "risks",
    "assumptions",
    "salience",
    "signals",
    "status",
    "storage",
    "triage",
    "trust",
    "vitality",
}


class GoldenFileMismatchError(AssertionError):
    pass


def _load_golden(name: str) -> str | None:
    golden_path = GOLDEN_DIR / f"{name}.golden"
    if golden_path.exists():
        return golden_path.read_text(encoding="utf-8")
    return None


def _save_golden(name: str, content: str) -> None:
    GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
    (GOLDEN_DIR / f"{name}.golden").write_text(content, encoding="utf-8")


def _compare_with_golden(name: str, actual: str, update: bool) -> None:
    golden = _load_golden(name)
    if update or golden is None:
        _save_golden(name, actual)
        if golden is None:
            pytest.skip(f"Created new golden file: {name}.golden")
        return

    if actual != golden:
        diff = "".join(
            difflib.unified_diff(
                golden.splitlines(keepends=True),
                actual.splitlines(keepends=True),
                fromfile=f"{name}.golden",
                tofile="actual",
            )
        )
        raise GoldenFileMismatchError(
            f"Output does not match golden file: {name}.golden\n\nDiff:\n{diff}"
        )


def test_intent_router_deterministic_routes_snapshot(update_golden: bool) -> None:
    router = IntentRouter()
    payload = []
    for request in REQUESTS:
        invocation = router.route(request)
        payload.append(
            {
                "request": request,
                "command": invocation.command,
                "args": list(invocation.args),
                "warnings": list(invocation.warnings),
                "rendered": render_invocation(invocation),
            }
        )
    actual = json.dumps(payload, indent=2) + "\n"
    _compare_with_golden(GOLDEN_NAME, actual, update_golden)


def test_intent_router_read_only_command_family_coverage_floor() -> None:
    router = IntentRouter()
    actual_families = {router.route(request).command for request in READ_ONLY_REQUESTS}
    missing = READ_ONLY_COMMAND_FAMILIES - actual_families

    assert not missing
    coverage = len(actual_families & READ_ONLY_COMMAND_FAMILIES) / len(READ_ONLY_COMMAND_FAMILIES)
    assert coverage >= 0.90