"""Program-directory path registry — the single Zone-A source of truth for
where platform-owned artifacts live under ``programs/<id>/``.

This module is the deliverable of ``specs/declutter.md`` Phase 0.5 / 1-B and
realizes goal G-7 (single source of truth for the directory taxonomy). Two
explicit registries drive every consumer:

* ``RUNTIME_ARTIFACTS`` — the T-3 platform-internal files that live in
  ``runtime/`` after the Phase 1-B flip. Each entry pairs a **canonical write
  getter** (``get_*_path`` — always returns ``runtime/<file>``; **never falls
  back**) with a **transitional read resolver** (``resolve_*_path_for_read`` —
  canonical-first, legacy fallback during the Phase 1 compatibility window;
  carries a ``# TODO-DC02`` marker to be removed per Phase 1-E). R-14: a
  writer must never call a fallback resolver, or active programs keep writing
  the legacy root path and create split-brain state.

* ``ROOT_ENTRIES`` — the T-1 authored config, T-2 mutable state, root T-4
  append-only logs, hidden markers, and recognized subdirectories. This is the
  whitelist ``DC-01-c`` derives from.

Phase 1-B status (2026-06-23): getters return ``runtime/<file>``; resolvers
prefer canonical and fall back to the legacy root during the transition window.
All ~22 production call sites already route through the correct getter or
resolver from Phase 0.5, so no call-site changes are needed.

``PROGRAMS_ROOT`` is imported from ``config_loader`` (the foundational default
used by most stores). Edition-resolution paths continue to use
``edition_resolver``'s env-aware root; runtime-path callers pass an explicit
``programs_root`` in tests, so the default source does not diverge in practice.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Literal

from src.core.config_loader import PROGRAMS_ROOT

# Subdirectory that collects platform-internal T-3 files (Phase 1-A).
RUNTIME_SUBDIR = "runtime"


def get_runtime_dir(program_id: str, *, programs_root: Path = PROGRAMS_ROOT) -> Path:
    """Canonical path for the platform-internal ``runtime/`` subdir.

    Phase 1-A: writers construct canonical runtime paths as
    ``get_runtime_dir(program_id, programs_root=...) / artifact.filename``.
    """
    return programs_root / program_id / RUNTIME_SUBDIR


# ---------------------------------------------------------------------------
# Runtime-artifact registry (T-3 files that move into runtime/)
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class RuntimeArtifact:
    """One platform-internal T-3 file with its tier and delete-safety contract.

    ``canonical_getter_name`` names the write getter (no legacy fallback);
    ``read_resolver_name`` names the transitional read resolver (canonical-first,
    legacy fallback during the Phase 1 compatibility window).
    """

    name: str
    filename: str
    tier: Literal["T-3a", "T-3b"]
    legacy_rel: PurePosixPath
    canonical_rel: PurePosixPath
    delete_safe: bool
    retention: str
    canonical_getter_name: str
    read_resolver_name: str
    checkpointed: bool = False


def _runtime(filename: str) -> PurePosixPath:
    return PurePosixPath(RUNTIME_SUBDIR) / filename


# Vertex analytics rebuild is NOT lossless from primaries today: the rebuild
# path destroys ``dri_response_log`` and ``contradiction_state`` without
# repopulating them (specs/declutter.md A-11). Per A-11's "action if false",
# vertex_analytics is reclassified T-3b and added to checkpoint protection so
# Phase 1 migration never treats it as disposable (G-5 zero silent data loss).
# m365_registry.yaml holds pm_confirmed promotions; per §5 it is either
# checkpointed or accepted as re-discoverable. We checkpoint it (G-5).
RUNTIME_ARTIFACTS: tuple[RuntimeArtifact, ...] = (
    RuntimeArtifact(
        name="gather_state",
        filename="gather_state.json",
        tier="T-3b",
        legacy_rel=PurePosixPath("gather_state.json"),
        canonical_rel=_runtime("gather_state.json"),
        delete_safe=False,
        retention="CONFIDENTIAL 1yr; recoverable by gather with re-fetch cost",
        canonical_getter_name="get_gather_state_path",
        read_resolver_name="resolve_gather_state_path_for_read",
        checkpointed=False,
    ),
    RuntimeArtifact(
        name="run_telemetry",
        filename="run_telemetry.jsonl",
        tier="T-3a",
        legacy_rel=PurePosixPath("run_telemetry.jsonl"),
        canonical_rel=_runtime("run_telemetry.jsonl"),
        delete_safe=True,
        retention="historical per-run latency log; regenerated by gather",
        canonical_getter_name="get_run_telemetry_path",
        read_resolver_name="resolve_run_telemetry_path_for_read",
        checkpointed=False,
    ),
    RuntimeArtifact(
        name="dedup_drop_log",
        filename="dedup_drop_log.jsonl",
        tier="T-3a",
        legacy_rel=PurePosixPath("dedup_drop_log.jsonl"),
        canonical_rel=_runtime("dedup_drop_log.jsonl"),
        delete_safe=True,
        retention="dedup audit trail; regenerated by gather",
        canonical_getter_name="get_dedup_drop_log_path",
        read_resolver_name="resolve_dedup_drop_log_path_for_read",
        checkpointed=False,
    ),
    RuntimeArtifact(
        name="vertex_analytics",
        filename="vertex_analytics.sqlite3",
        tier="T-3b",
        legacy_rel=PurePosixPath("vertex_analytics.sqlite3"),
        canonical_rel=_runtime("vertex_analytics.sqlite3"),
        delete_safe=False,
        retention="analytics projection; rebuild not lossless (A-11) — checkpointed",
        canonical_getter_name="get_program_analytics_store_path",
        read_resolver_name="resolve_program_analytics_store_path_for_read",
        checkpointed=True,
    ),
    RuntimeArtifact(
        name="readiness_snapshot",
        filename="readiness_snapshot.yaml",
        tier="T-3a",
        legacy_rel=PurePosixPath("readiness_snapshot.yaml"),
        canonical_rel=_runtime("readiness_snapshot.yaml"),
        delete_safe=True,
        retention="last readiness snapshot; regenerated by `vertex readiness fetch`",
        canonical_getter_name="get_readiness_snapshot_path",
        read_resolver_name="resolve_readiness_snapshot_path_for_read",
        checkpointed=False,
    ),
    RuntimeArtifact(
        name="m365_registry",
        filename="m365_registry.yaml",
        tier="T-3b",
        legacy_rel=PurePosixPath("m365_registry.yaml"),
        canonical_rel=_runtime("m365_registry.yaml"),
        delete_safe=False,
        retention="M365 discovery cache + pm_confirmed promotions; checkpointed (G-5)",
        canonical_getter_name="get_m365_registry_path",
        read_resolver_name="resolve_m365_registry_path_for_read",
        checkpointed=True,
    ),
    RuntimeArtifact(
        name="channel_registry",
        filename="channel_registry.sqlite3",
        tier="T-3b",
        legacy_rel=PurePosixPath("channel_registry.sqlite3"),
        canonical_rel=_runtime("channel_registry.sqlite3"),
        delete_safe=False,
        retention="per-channel signal state + pm_confirmed registrations; checkpointed",
        canonical_getter_name="get_channel_registry_path",
        read_resolver_name="resolve_channel_registry_path_for_read",
        checkpointed=True,
    ),
)

RUNTIME_ARTIFACTS_BY_NAME: dict[str, RuntimeArtifact] = {a.name: a for a in RUNTIME_ARTIFACTS}
RUNTIME_FILENAMES: frozenset[str] = frozenset(a.filename for a in RUNTIME_ARTIFACTS)
CHECKPOINTED_RUNTIME_ARTIFACTS: tuple[RuntimeArtifact, ...] = tuple(
    a for a in RUNTIME_ARTIFACTS if a.checkpointed
)


# ---------------------------------------------------------------------------
# Root-entry registry (T-1 / T-2 / root T-4 / hidden markers / recognized dirs)
# ---------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class RootEntry:
    """A recognized entry at the program root (file, directory, or marker).

    ``kind`` is ``"file"``, ``"dir"``, or ``"marker"``. The DC-01-c whitelist is
    the union of all root-entry names plus all runtime-artifact legacy names.
    """

    name: str
    tier: str
    kind: Literal["file", "dir", "marker"]


ROOT_ENTRIES: tuple[RootEntry, ...] = (
    # T-1 authored config (operator-owned, stable)
    RootEntry("program.yaml", "T-1", "file"),
    RootEntry("workstreams.yaml", "T-1", "file"),
    RootEntry("scorecards.yaml", "T-1", "file"),
    RootEntry("editorial_rules.yaml", "T-1", "file"),
    RootEntry("review.yaml", "T-1", "file"),
    RootEntry("chapter_contract.yaml", "T-1", "file"),
    RootEntry("template_contract.yaml", "T-1", "file"),
    RootEntry("slice_contracts.yaml", "T-1", "file"),
    RootEntry("source_contracts.yaml", "T-1", "file"),
    RootEntry("source_waivers.yaml", "T-1", "file"),
    RootEntry("kpis.yaml", "T-1", "file"),
    RootEntry("backfill.yaml", "T-1", "file"),
    RootEntry("escalation_rules.yaml", "T-1", "file"),
    RootEntry("ado_comment_template.md", "T-1", "file"),
    # T-2 mutable program state (operator + platform)
    RootEntry("baseline.yaml", "T-2", "file"),
    RootEntry("trusted_baseline.yaml", "T-2", "file"),
    RootEntry("decisions.yaml", "T-2", "file"),
    RootEntry("assumptions.yaml", "T-2", "file"),
    RootEntry("dependencies.yaml", "T-2", "file"),
    RootEntry("risk_register.yaml", "T-2", "file"),
    RootEntry("milestones.yaml", "T-2", "file"),
    RootEntry("manual_metrics.yaml", "T-2", "file"),
    RootEntry("readiness.yaml", "T-2", "file"),
    RootEntry("earned_autonomy_state.yaml", "T-2", "file"),
    RootEntry("capability_status.yaml", "T-2", "file"),
    RootEntry("fact_store_sor.yaml", "T-2", "file"),
    RootEntry("workstream_registry.yaml", "T-2", "file"),
    # Root T-4 append-only logs (platform-owned, grow-only)
    RootEntry("chronicle.jsonl", "T-4", "file"),
    RootEntry("external_dependencies.jsonl", "T-4", "file"),
    RootEntry("migration_log.jsonl", "T-4", "file"),
    RootEntry("platform_proof_log.yaml", "T-4", "file"),
    # Hidden markers (tool-specific)
    RootEntry(".edition_layout.json", "marker", "marker"),
    RootEntry(".migration_manifest.json", "marker", "marker"),
    RootEntry(".runtime_migration_manifest.json", "marker", "marker"),
    # Recognized subdirectories
    RootEntry("editions", "T-1", "dir"),
    RootEntry("knowledge", "T-1", "dir"),
    RootEntry("journal", "T-4", "dir"),
    RootEntry("journal_archive", "T-4", "dir"),
    RootEntry("ledger", "T-4", "dir"),
    RootEntry("trajectories", "T-4", "dir"),
    RootEntry("changelog", "T-4", "dir"),
    RootEntry("publications", "T-5", "dir"),
    RootEntry("archive", "T-5", "dir"),
    RootEntry("narratives", "T-6", "dir"),
    RootEntry("summaries", "T-6", "dir"),
    RootEntry("nudge", "T-6", "dir"),
    RootEntry("overrides", "T-6", "dir"),
    RootEntry("checkpoints", "T-6", "dir"),
    RootEntry("metrics", "T-6", "dir"),
    RootEntry("backfill", "T-6", "dir"),
    RootEntry("gold_corpus", "T-6", "dir"),
    RootEntry("_state", "T-3-class", "dir"),
    RootEntry("_alerts", "T-3-class", "dir"),
    RootEntry("_feedback", "T-7", "dir"),
    RootEntry("_spike", "T-8", "dir"),
    RootEntry("docs", "T-8", "dir"),
    RootEntry("runtime", "T-3", "dir"),
)

# Names recognized at the program root (files + markers + dirs).
ROOT_ENTRY_NAMES: frozenset[str] = frozenset(e.name for e in ROOT_ENTRIES)
# DC-01-c whitelist: recognized root entries plus runtime-artifact legacy
# filenames (which still legitimately appear at root during the transition).
ROOT_WHITELIST: frozenset[str] = ROOT_ENTRY_NAMES | RUNTIME_FILENAMES
# Root-level T-2 files — surfaced via DC-01-c metadata to drive the Phase 3
# state/ trigger (declutter.md §6 Phase 3).
ROOT_T2_FILES: tuple[str, ...] = tuple(e.name for e in ROOT_ENTRIES if e.tier == "T-2")


# ---------------------------------------------------------------------------
# Canonical write getters (Phase 1-B: return runtime/ path; NEVER fall back)
#
# R-14: writers call ONLY these getters. Callers that also need to read before
# the first write (i.e. load-or-create patterns) must use the read resolver to
# pick up the legacy file if it hasn't been migrated yet, then write back via
# the canonical getter path.
# ---------------------------------------------------------------------------


def get_gather_state_path(program_id: str, *, programs_root: Path = PROGRAMS_ROOT) -> Path:
    """Canonical write path for the gather ingest-resumption cursor (runtime/)."""
    return programs_root / program_id / RUNTIME_SUBDIR / "gather_state.json"


def get_run_telemetry_path(program_id: str, *, programs_root: Path = PROGRAMS_ROOT) -> Path:
    """Canonical write path for the per-run telemetry JSONL sidecar (runtime/)."""
    return programs_root / program_id / RUNTIME_SUBDIR / "run_telemetry.jsonl"


def get_dedup_drop_log_path(program_id: str, *, programs_root: Path = PROGRAMS_ROOT) -> Path:
    """Canonical write path for the dedup drop-log JSONL sidecar (runtime/)."""
    return programs_root / program_id / RUNTIME_SUBDIR / "dedup_drop_log.jsonl"


def get_m365_registry_path(program_id: str, *, programs_root: Path = PROGRAMS_ROOT) -> Path:
    """Canonical write path for the M365 discovery registry (runtime/)."""
    return programs_root / program_id / RUNTIME_SUBDIR / "m365_registry.yaml"


def get_channel_registry_path(program_id: str, *, programs_root: Path = PROGRAMS_ROOT) -> Path:
    """Canonical write path for the per-channel signal-state SQLite registry (runtime/)."""
    return programs_root / program_id / RUNTIME_SUBDIR / "channel_registry.sqlite3"


def get_program_analytics_store_path(program_id: str, *, programs_root: Path = PROGRAMS_ROOT) -> Path:
    """Canonical write path for the vertex analytics SQLite projection (runtime/)."""
    return programs_root / program_id / RUNTIME_SUBDIR / "vertex_analytics.sqlite3"


def get_readiness_snapshot_path(program_id: str, *, programs_root: Path = PROGRAMS_ROOT) -> Path:
    """Canonical write path for the readiness snapshot (runtime/)."""
    return programs_root / program_id / RUNTIME_SUBDIR / "readiness_snapshot.yaml"


def get_platform_proof_log_path(program_id: str, *, programs_root: Path = PROGRAMS_ROOT) -> Path:
    """Path for the platform proof log (T-4 root; never moves to runtime/)."""
    return programs_root / program_id / "platform_proof_log.yaml"


# ---------------------------------------------------------------------------
# Transitional read resolvers (Phase 1-B)
#
# Prefer the canonical ``runtime/`` path; fall back to the legacy root only
# when the canonical file does not yet exist (pre-migration window). The
# fallback branches carry ``# TODO-DC02`` markers and are removed per the
# Phase 1-E lifecycle (command-matrix gate + 2 clean DC-02 runs).
#
# R-14: writers MUST NOT call these resolvers — use the canonical write getter.
# ---------------------------------------------------------------------------


def resolve_gather_state_path_for_read(program_id: str, *, programs_root: Path = PROGRAMS_ROOT) -> Path:
    canonical = get_gather_state_path(program_id, programs_root=programs_root)
    if not canonical.exists():
        legacy = programs_root / program_id / "gather_state.json"
        if legacy.exists():
            return legacy  # TODO-DC02 transition fallback; remove per Phase 1-E
    return canonical


def resolve_run_telemetry_path_for_read(program_id: str, *, programs_root: Path = PROGRAMS_ROOT) -> Path:
    canonical = get_run_telemetry_path(program_id, programs_root=programs_root)
    if not canonical.exists():
        legacy = programs_root / program_id / "run_telemetry.jsonl"
        if legacy.exists():
            return legacy  # TODO-DC02 transition fallback; remove per Phase 1-E
    return canonical


def resolve_dedup_drop_log_path_for_read(program_id: str, *, programs_root: Path = PROGRAMS_ROOT) -> Path:
    canonical = get_dedup_drop_log_path(program_id, programs_root=programs_root)
    if not canonical.exists():
        legacy = programs_root / program_id / "dedup_drop_log.jsonl"
        if legacy.exists():
            return legacy  # TODO-DC02 transition fallback; remove per Phase 1-E
    return canonical


def resolve_m365_registry_path_for_read(program_id: str, *, programs_root: Path = PROGRAMS_ROOT) -> Path:
    canonical = get_m365_registry_path(program_id, programs_root=programs_root)
    if not canonical.exists():
        legacy = programs_root / program_id / "m365_registry.yaml"
        if legacy.exists():
            return legacy  # TODO-DC02 transition fallback; remove per Phase 1-E
    return canonical


def resolve_channel_registry_path_for_read(program_id: str, *, programs_root: Path = PROGRAMS_ROOT) -> Path:
    canonical = get_channel_registry_path(program_id, programs_root=programs_root)
    if not canonical.exists():
        legacy = programs_root / program_id / "channel_registry.sqlite3"
        if legacy.exists():
            return legacy  # TODO-DC02 transition fallback; remove per Phase 1-E
    return canonical


def resolve_program_analytics_store_path_for_read(
    program_id: str, *, programs_root: Path = PROGRAMS_ROOT
) -> Path:
    canonical = get_program_analytics_store_path(program_id, programs_root=programs_root)
    if not canonical.exists():
        legacy = programs_root / program_id / "vertex_analytics.sqlite3"
        if legacy.exists():
            return legacy  # TODO-DC02 transition fallback; remove per Phase 1-E
    return canonical


def resolve_readiness_snapshot_path_for_read(program_id: str, *, programs_root: Path = PROGRAMS_ROOT) -> Path:
    canonical = get_readiness_snapshot_path(program_id, programs_root=programs_root)
    if not canonical.exists():
        legacy = programs_root / program_id / "readiness_snapshot.yaml"
        if legacy.exists():
            return legacy  # TODO-DC02 transition fallback; remove per Phase 1-E
    return canonical